### ISSUE TITLE
Request for a method to run indexer

### ISSUE THREAD

**Issue by parijatsahai** [azure-contrib/node-azure-search#11]
In the documentation or code, I don't see a method that allows one to run an indexer. Could you please add this at the earliest convenience? It'll be very helpful.
Please refer to the following Azure documentation: https://msdn.microsoft.com/en-us/library/azure/dn946885.aspx

**Comment by alancnet** [comment]
@richorama I believe this issue can be closed, as @parijatsahai contributed the code [the very same day](https://github.com/azure-contrib/node-azure-search/commit/89f5b3e6e7a0041899f9c38dc1ff9dffa789781d).

**Comment by alancnet** [comment]
PS @parijatsahai, consider going to [Email settings](https://github.com/settings/emails) to add your disassociated email address pa***at@re****ex.com so commits made with that email are associated to your account.
