### ISSUE TITLE
updateIndex error

### ISSUE THREAD

**Issue by HKskn** [azure-contrib/node-azure-search#29]
Hello, I try to run something like code below

client.updateIndex('myindex', schema, function(err){
  // optional error
});

it gives me an error that tells "message: 'Existing field \'username\' cannot be changed.' } "
I guess updateIndex only works to add new fields. Could you give me some information about it? If updateIndex does not support to edit existing field, Could you add this feature to edit existing field?

**Comment by richorama** [comment]
Hi @HKskn 

This library is only a thin wrapper around the Microsoft API, so it doesn't introduce any limitation, it's just passing on an error from the search service.

According to the Microsoft documentation, only updates to the schema are supported:

https://docs.microsoft.com/en-us/rest/api/searchservice/update-index

I suggest raising an issue with them :¬)

Hope that helps...
