### ISSUE TITLE
All indexer create attempts fail with "The underlying connection was closed: An unexpected error occurred on a send"

### ISSUE THREAD

**Issue by alonisser** [azure-contrib/node-azure-search#33]
Please note that dataSource and search index are created ok, just the indexer create

**Comment by richorama** [comment]
Thanks for reporting this @alonisser.

Is this a transient error, or are you still seeing it?

**Comment by alonisser** [comment]
Still seeing this, also happening from the Azure UI.. I'm with support on searching for this error

**Comment by richorama** [comment]
it sounds like a problem with the service rather than this library, but let's keep the issue open whilst you're diagnosing it.

**Comment by alonisser** [comment]
Yap, turned out to be a problem with the service, and swallowing the true error and emitting this instead (not the lib, in azure side)
