### ISSUE TITLE
Way to add headers to POST requests

### ISSUE THREAD

**Issue by alonisser** [azure-contrib/node-azure-search#34]
Following the docs, [a recommended way of tracking requests is adding headers](https://docs.microsoft.com/en-us/azure/search/search-traffic-analytics#how-to-implement-search-traffic-analytics) But following the code search method uses ```post``` method which does not pass ```overriders``` to ```execution``` function, which is the way to pass headers.  Is there a work around this ? A recommended technical design for a PR?

**Comment by richorama** [comment]
Good point.

I think adding additional headers on the `options` object in the module's constructor is the most simple solution. 

The only problem is that you'll need to create a new instance of the search client when you want a new value for the header.

To clarify, I mean this:

```js
var client = AzureSearch({
  url: "https://XXX.search.windows.net",
  key: "YYY",
  headers : { "x-my-custom-header" : "foo"  }
});
```
